/**
 * models/Quiz.js
 *
 * PURPOSE:
 * A generated set of quiz questions for a subject (optionally scoped to
 * one topic, e.g. Rescue Mode re-quizzes). Questions are embedded
 * sub-documents since they are never queried independently of their quiz.
 *
 * CONNECTS TO:
 * - controllers/quizController.js (generate + submit)
 * - controllers/rescueController.js (creates rescue-scoped quizzes)
 * - models/QuizAttempt.js (stores the student's answers against this quiz)
 */

const mongoose = require("mongoose");

const questionSchema = new mongoose.Schema(
  {
    question: { type: String, required: true },
    options: { type: [String], required: true },
    correctAnswer: { type: String, required: true },
    explanation: { type: String, default: "" },
    topic: { type: String, required: true, trim: true },
    difficulty: { type: String, enum: ["easy", "medium", "hard"], default: "medium" },
  },
  { _id: true }
);

const quizSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    subject: { type: String, required: true, trim: true },
    note: { type: mongoose.Schema.Types.ObjectId, ref: "Note", default: null },

    // "initial" quizzes come from the first note analysis.
    // "rescue" quizzes are generated by Rescue Mode for one weak topic.
    // "adaptive" quizzes are generated by quizService's ranking algorithm.
    type: { type: String, enum: ["initial", "rescue", "adaptive"], default: "initial" },
    focusTopic: { type: String, default: null }, // set when type === "rescue"

    questions: [questionSchema],
  },
  { timestamps: true }
);

module.exports = mongoose.model("Quiz", quizSchema);
